import os
import sys
import re
import datetime
from numbers_parser import Document

PRODUCT_MAPPING = {
    "XỊT DƯỠNG CHUYÊN SÂU": "xit-duong-chuyen-sau-miracle",
    "TINH CHẤT TÁI SINH VI SINH 2.0": "tinh-chat-tai-sinh-2-0",
    "TINH CHẤT TÁI SINH VI SINH 2.7": "tinh-chat-tai-sinh-2-7",
    "SỮA RỬA MẶT NƯỚC BĂNG": "sua-rua-mat-nuoc-bang-glacier",
    "KEM CHỐNG NẮNG PHỔ RỘNG": "kem-chong-nang-smart-suncare",
    "COMBO 1": "combo-1-trang-sang",
    "COMBO 2": "combo-2-phuc-hoi",
    "COMBO 3": "combo-3-toan-dien",
    "COMBO 4": "combo-4-tinh-gon",
    "Chải khô mặt": "chai-kho-mat",
    "Guasha": "guasha",
    "Chải khô cơ thể": "chai-kho-co-the",
    "Toner Hoa hồng": "toner-hoa-hong",
    "Toner Tía tô": "toner-tia-to",
    "Toner Hoa cúc": "toner-hoa-cuc",
    "Tinh chất hoa bưởi": "tinh-chat-hoa-buoi",
    "Nước tẩy trang Tía tô & Hoa hồng": "nuoc-tay-trang-tia-to-hoa-hong",
    "Xà bông Nghệ Hoa hồng": "xa-bong-nghe-hoa-hong",
    "Xà bông Gừng Tràm Quế": "xa-bong-gung-tram-que",
    "Mặt nạ hoa hồng": "mat-na-hoa-hong",
    "Mặt nạ tía tô": "mat-na-tia-to",
    "Mặt nạ nghệ phục hồi": "mat-na-nghe-phuc-hoi",
    "Dầu dưỡng hoa hồng": "dau-duong-hoa-hong",
    "Cao gội Hoa hồng 2 in 1": "cao-goi-hoa-hong-2-in-1-goixa",
    "Trà Hoa hồng": "tra-hoa-hong",
    "Trà Tía tô": "tra-tia-to",
    "Gấc lên men": "gac-len-men",
    "Gừng Quất Muối": "mat-ong-gung-quat-muoi",
    "Cốt nghệ Mật Ong lên men": "cot-nghe-mat-ong-len-men"
}

def map_product_name(raw_name):
    if not raw_name:
        return None
    name = raw_name.strip().replace('\n', ' ')
    
    # Try direct mapping first
    if name in PRODUCT_MAPPING:
        return PRODUCT_MAPPING[name]
        
    # Try partial matching from the keys of PRODUCT_MAPPING
    for key, value in PRODUCT_MAPPING.items():
        if name.startswith(key) or key.startswith(name):
            return value
            
    return None

def get_deterministic_date(product_id, review_idx):
    # Base date: 2026-05-28
    base_date = datetime.date(2026, 5, 28)
    char_sum = sum(ord(c) for c in product_id)
    offset = char_sum % 15
    days_ago = 5 + review_idx * 22 + offset
    review_date = base_date - datetime.timedelta(days=days_ago)
    return review_date.strftime("%d/%m/%Y")

def main():
    # Find .numbers file
    files = [f for f in os.listdir('.') if f.endswith('.numbers')]
    if not files:
        print("Error: No .numbers file found in current directory.", file=sys.stderr)
        sys.exit(1)
        
    filename = files[0]
    print(f"Opening file: {filename}")
    
    doc = Document(filename)
    table = doc.sheets[0].tables[0]
    
    reviews_pattern = re.compile(
        r'(?:^|\n|\r)\s*(?:\d+\.\s*)?(Chị|Anh|Chi)\s+([^:\n\r]+?)\s*:\s*'
    )
    
    extracted_reviews = []
    skipped_products = []
    
    for row_idx in range(2, table.num_rows):
        prod_name_cell = table.cell(row_idx, 2).value
        reviews_cell = table.cell(row_idx, 18).value
        
        if not prod_name_cell:
            continue
            
        prod_id = map_product_name(prod_name_cell)
        if not prod_id:
            print(f"Warning: Could not map product name: {repr(prod_name_cell)}")
            continue
            
        if not reviews_cell:
            skipped_products.append(prod_name_cell)
            continue
            
        reviews_text = str(reviews_cell)
        matches = list(reviews_pattern.finditer(reviews_text))
        
        if not matches:
            print(f"Warning: No reviews parsed for product '{prod_name_cell}' despite having review text: {repr(reviews_text)}")
            continue
            
        for i, match in enumerate(matches):
            prefix = match.group(1)
            name = match.group(2).strip()
            user_name = f"{prefix} {name}"
            
            start_pos = match.end()
            end_pos = matches[i+1].start() if i+1 < len(matches) else len(reviews_text)
            
            comment = reviews_text[start_pos:end_pos].strip()
            comment = comment.strip(' \n\r\t"“”\'‘’')
            
            if not comment:
                continue
                
            date_str = get_deterministic_date(prod_id, len([r for r in extracted_reviews if r['productId'] == prod_id]))
            
            extracted_reviews.append({
                "productId": prod_id,
                "userName": user_name,
                "rating": 5,
                "comment": comment,
                "date": date_str,
                "isVerifiedPurchase": True
            })

    # Write TypeScript seed data file
    output_path = 'prisma/reviews_seed_data.ts'
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("/*\n")
        f.write(" * This file was auto-generated by extract_reviews.py\n")
        f.write(" * Do not edit this file directly.\n")
        f.write(" */\n\n")
        f.write("export interface ReviewSeed {\n")
        f.write("  productId: string;\n")
        f.write("  userName: string;\n")
        f.write("  rating: number;\n")
        f.write("  comment: string;\n")
        f.write("  date: string;\n")
        f.write("  isVerifiedPurchase: boolean;\n")
        f.write("}\n\n")
        f.write("export const reviewsSeedData: ReviewSeed[] = [\n")
        
        for r in extracted_reviews:
            # Escape backslashes and double quotes in comment
            escaped_comment = r['comment'].replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')
            f.write("  {\n")
            f.write(f"    productId: \"{r['productId']}\",\n")
            f.write(f"    userName: \"{r['userName']}\",\n")
            f.write(f"    rating: {r['rating']},\n")
            f.write(f"    comment: \"{escaped_comment}\",\n")
            f.write(f"    date: \"{r['date']}\",\n")
            f.write(f"    isVerifiedPurchase: {str(r['isVerifiedPurchase']).lower()}\n")
            f.write("  },\n")
            
        f.write("];\n")
        
    print(f"\nSuccessfully extracted {len(extracted_reviews)} reviews for {len(set(r['productId'] for r in extracted_reviews))} products.")
    print(f"Skipped products with no reviews: {', '.join(skipped_products)}")
    print(f"Generated seed file: {output_path}")

if __name__ == '__main__':
    main()
