/*
 * This file was auto-generated by extract_reviews.py
 * Do not edit this file directly.
 */

export interface ReviewSeed {
  productId: string;
  userName: string;
  rating: number;
  comment: string;
  date: string;
  isVerifiedPurchase: boolean;
}

export const reviewsSeedData: ReviewSeed[] = [
  {
    productId: "xit-duong-chuyen-sau-miracle",
    userName: "Chị Phương",
    rating: 5,
    comment: "Mình dùng xịt dưỡng thấy rất thích vì cảm giác tự nhiên, không mùi, không màu và thấm nhẹ trên da. Da mình trước đây hay bị mụn li ti, dùng hết 1 chai đã cải thiện rõ. Kết hợp đắp mặt nạ đều thì da căng bóng, mềm mịn hơn hẳn. Bao bì niêm phong kỹ nên cũng rất yên tâm khi sử dụng.",
    date: "22/05/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "xit-duong-chuyen-sau-miracle",
    userName: "Chị Hà",
    rating: 5,
    comment: "Da mình da dầu, thường xuyên bị mụn viêm tái đi tái lại, sau khi biết và sử dụng sản phẩm Mỹ phẩm vi sinh Hoa Ngân, mình không còn bị mụn viêm tái đi tái lại, da cũng cân bằng hơn rất nhiều, lại còn rất lành tính kiểm nghiệm đầy đủ nên mình rất tin tưởng.",
    date: "30/04/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "xit-duong-chuyen-sau-miracle",
    userName: "Chi Trinh",
    rating: 5,
    comment: "Món xịt dưỡng này rất tiện, mình là người lười skincare nhưng vẫn muốn da đẹp, gặp được giải pháp mỹ phẩm vi sinh Hoa Ngân như vi cứu tinh cho làn da bí tắc của mình. Mình lười nên thi thoảng mới đắp mặt nạ xịt dưỡng còn thông thường chỉ xịt ngày 3-5 lần, sau 1 tháng da mình khỏe đẹp lên rất nhiều. Các bạn tư vấn cũng rất nhiệt tình và theo sát quá trình sử dụng của mình",
    date: "08/04/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "tinh-chat-tai-sinh-2-0",
    userName: "Chị Linh",
    rating: 5,
    comment: "Sản phẩm tốt, lành tính, ấn tượng nhất là cam kết đồng hành tới khi da đẹp. Chắc là không mỹ phẩm ở đâu lại được cam kết và đồng hành sát sao với khách hàng như vậy. Đã sử dụng, da khỏe và căng bóng nhưng không bị mỏng đi khi dùng treatment. Sẽ mua thêm cho các mẹ các cô ở nhà sử dụng",
    date: "17/05/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "tinh-chat-tai-sinh-2-0",
    userName: "Chị Vân Anh",
    rating: 5,
    comment: "Da mình mỏng, yếu, thường xuyên lên mụn viêm và dễ kích ứng. Sau khi sử dụng da mình như tự điều tiết độ ẩm trên da luôn vậy, không còn bị quá khô hay quá dầu và cảm giác da thông thoáng, không bị lên mụn tái lại. Routine hàng ngày theo hướng dẫn của bạn tư vấn viên thì mình cũng chỉ xịt dưỡng và dùng vi sinh 2.7 & 2.0. Yên tâm khi sử dụng sản phẩm vì tư vấn viên quá nhiệt tình",
    date: "25/04/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "tinh-chat-tai-sinh-2-7",
    userName: "Chị Phương Anh",
    rating: 5,
    comment: "Da mình dày sừng, khô ráp và bị thâm mụn do hay cậy mụn viêm, sau khi sử dụng bộ sản phẩm vi sinh Hoa Ngân khoảng hơn 1 tháng thì da mềm ẩm tự nhiên hơn rất nhiều. Các nốt thâm mụn thì hết hẳn, các nốt tàn nhang cũng mờ đi. Vi sinh 2.7 khi dùng theo tư vấn sẽ loại bỏ lớp dày sừng có chọn lọc, giúp bổ sung lợi khuẩn để tái tạo làn da nên sẽ có hơi bong tróc nhưng bong xong da sẽ tái tạo lại nên sẽ khỏe hơn chứ không hề bị mỏng đi nhé. Hiếm thấy mỹ phẩm vi sinh nào bổ sung lợi khuẩn trực tiếp được như vậy. Mà lại lành tính kiểm nghiệm đầy đủ.",
    date: "10/05/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "tinh-chat-tai-sinh-2-7",
    userName: "Chị Lan Anh",
    rating: 5,
    comment: "Mình gặp vấn đề về da xỉn màu, lỗ chân lông to, hay bị đỏ ở cánh mũi, thi thoảng nổi mụn viêm ở cằm và trán dù đã 40 tuổi rồi. Mình đã chi tiền làm đẹp rất nhiều, treatment, spa nhưng chỉ được 1 thời gian rồi lại tái lại, mình cũng chán dùng hóa chất vì biết nó cũng không tốt. Được chị bạn giới thiệu cho vi sinh Hoa Ngân như 1 chân trời mới với mình, sau khi dùng 2 tháng da mình nó khỏe, nó láng, nó tự cân bằng mà không cần nhiều sản phẩm, nó thích gì đâu, da láng lại còn cải thiện lão hóa, căng bóng nhưng nên kết hợp phi kim tại nhà nữa nha. Con gái mình đang tuổi dậy thì bị mụn mình cũng cho xài vi sinh Hoa Ngân luôn, vừa giúp da láng sạch mà còn lành tính.",
    date: "18/04/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "tinh-chat-tai-sinh-2-7",
    userName: "Anh Tuấn",
    rating: 5,
    comment: "Do stress công việc và cũng không biết chăm sóc da nên mình bị nổi mụn rất nhiều, sau khi được biết đến và sử dụng mỹ phẩm vi sinh Hoa Ngân, từ làn da thô ráp sần sùi mình đã có 1 làn da khỏe mạnh, trơn láng, nhìn sạch sẽ hơn rất nhiều đã giúp mình tự tin hơn trong giao tiếp và công việc. Dùng vi sinh 2.7 giúp mình gom cồi mụn từ sâu dưới da 1 cách nhẹ nhàng, mình cũng không cần nặn gì nhiều, khi mụn gom cồi chỉ cần bóp nhẹ là ra. Highly recommend sản phẩm lành tính này",
    date: "27/03/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "tinh-chat-tai-sinh-2-7",
    userName: "Chị Thiên Hương",
    rating: 5,
    comment: "Mình xài vi sinh Hoa Ngân được nửa năm rồi, da mình từ làn da lốm đóm thâm mụn, lỗ chân lông to ở 2 cánh mũi, xỉn màu do lo nghĩ công việc, giờ đã vô cùng ổn định, láng sạch không lên mụn viêm hay mụn ẩn nữa, da cũng sãng hơn nhiều. Vì quá thích nên mình mua cho cả mẹ xài, mẹ mình do hay mua mỹ phẩm linh tinh trên manjng nên da bị nhiễm hóa chất bị thâm nám khá nhiều, sau 3 tháng da mẹ mình cũng đã những cải thiện nhiều, vùng nám mờ đi nhiều, vùng bọng mắt chảy sệ cũng được nâng cơ, nghe bạn tư vấn viên nói nếu kết hợp phi kim sẽ cải thiện nhiều hơn nên mình cũng đang thử",
    date: "05/03/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "sua-rua-mat-nuoc-bang-glacier",
    userName: "Chị Trang",
    rating: 5,
    comment: "Sữa rửa mặt dịu nhẹ, không mùi không màu, rửa xong da không bị khô rít, da thoáng sạch",
    date: "22/05/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "sua-rua-mat-nuoc-bang-glacier",
    userName: "Anh Khánh",
    rating: 5,
    comment: "Sữa rửa mặt này làm sạch dịu nhẹ nha, không có chất tẩy rửa mạnh nên bảo vệ hàng rào bảo vệ da. Mình dùng thấy ok lắm nhé",
    date: "30/04/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "kem-chong-nang-smart-suncare",
    userName: "Chị Kim Anh",
    rating: 5,
    comment: "Kem chống nắng mỏng nhẹ, texture như kem dưỡng vậy á, không bí da",
    date: "20/05/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "combo-1-trang-sang",
    userName: "Chị Minh Anh",
    rating: 5,
    comment: "Trời ơi, mỹ phẩm Việt Nam có thể là đỉnh vậy sao. Không hóa chất mà lại hiệu quả, cách sử dụng thì đơn giản phù hợp với mọi lứa tuổi và cả những người lười nhất như mình. Các bạn cứ đọc bảng thành phần ngắn gọn của Xịt dưỡng và Vi sinh sẽ thấy toàn chiết xuất từ thảo dược Việt Nam và lợi khuẩn sống. Mình đã dùng và có được làn da mơ ước, xài sớm đẹp sớm nha mấy bà ơi",
    date: "11/05/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "combo-2-phuc-hoi",
    userName: "Chị Linh Anh",
    rating: 5,
    comment: "Sau 1 hồi cân nhắc thì mình quyết định mua bộ này, đầy đủ tất cả các sản phẩm của Hoa Ngân luôn. Thấy kem chống năng dùng khá ổn, mỏng nhẹ không bị bí da mà chống nắng phổ rộng nữa. Nhưng cốt lõi vẫn là 3 sản phẩm dưỡng còn lại giúp da mình khỏe mạnh và láng mịn hơn.",
    date: "13/05/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "combo-3-toan-dien",
    userName: "Chị Hà My",
    rating: 5,
    comment: "Combo này mình xài hoài. Mình đã mua rất nhiều lần, đơn giản mà hiệu quả. 1 năm chắc là chỉ cần 1 chai vi sinh 2.7 với vài combo này là da mình đẹp hoài được luôn",
    date: "19/05/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "combo-4-tinh-gon",
    userName: "Chị Lan",
    rating: 5,
    comment: "Combo này là combo chuẩn cho những ai mới nhập môn vi sinh Hoa Ngân nhé, nên đổi thành 1 vi sinh 2.0 và 1 vi sinh 2.7 thay vì lấy 2 chai vi sinh 2.7, vi sinh 2.7 để cân bằng lúc đầu khi da còn xấu còn vi sinh 2.0 là để duy trì nha. Da khỏe, láng sạch lên rất nhiều nè",
    date: "19/05/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "combo-4-tinh-gon",
    userName: "Anh Lộc",
    rating: 5,
    comment: "Mình bị viêm da tiết bã lâu năm, da thường xuyên đổ dầu, ửng đỏ vùng mũi cằm và trán, hay nổi mụn viêm khá đau và khó chịu nhất là khi lo nghĩ công việc. Sau khi dùng vi sinh Hoa Ngân, tình trạng da mình đã cải thiện rất nhiều, da cân bằng hơn và không còn bị ửng đỏ. Mụn viêm cũng không xuất hiện nhiều.",
    date: "27/04/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "combo-4-tinh-gon",
    userName: "Chị Mỹ",
    rating: 5,
    comment: "Mình ngưng sử dụng mỹ phẩm hóa chất được hơn 1 năm và tìm đến những phương pháp lành tính hơn, tuy nhiên sau thời gian cai mỹ phẩm hóa chất da mình vẫn bị mụn viêm tái đi tái lại và khá mất cân bằng độ ẩm nên lúc khô lúc dầu. Cho đến khi mình biết về chăm sóc hàng rào bảo vệ da và hệ vi sinh trên da và sử dụng Mỹ phẩm vi sinh Hoa Ngân thì da mình như được quay trở lại thời 19 tuổi, láng sạch căng và luôn ẩm tư nhiên. Tự hào Mỹ phẩm Việt Nam quá đi.",
    date: "05/04/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "chai-kho-mat",
    userName: "Chị Phương",
    rating: 5,
    comment: "Mình sử dụng chải khô mặt vào buổi sáng khoảng vài phút. Sau đó da trông tươi tắn hơn và các sản phẩm dưỡng da thấm tốt hơn.",
    date: "09/05/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "chai-kho-mat",
    userName: "Chị Linh",
    rating: 5,
    comment: "Da mình khá nhạy cảm nên rất lo khi thử chải khô mặt, nhưng lông chải mềm và dịu nhẹ. Dùng đều thấy da mịn màng và sáng khỏe hơn.",
    date: "17/04/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "chai-kho-mat",
    userName: "Chị Kim",
    rating: 5,
    comment: "Mình thích cảm giác thư giãn mà chải khô mặt mang lại. Mỗi sáng chải nhẹ nhàng giúp khuôn mặt trông bớt sưng và tỉnh táo hơn.",
    date: "26/03/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "guasha",
    userName: "Chị Hạnh",
    rating: 5,
    comment: "Mình duy trì guasha mặt khoảng 10 phút mỗi tối, sau vài tuần thấy gương mặt gọn hơn, vùng hàm và má cũng săn chắc hơn trước.",
    date: "20/05/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "guasha",
    userName: "Chị Lan",
    rating: 5,
    comment: "Trước đây mình hay bị căng cứng vùng vai gáy do ngồi máy tính nhiều. Dùng guasha kết hợp dầu massage giúp cơ thể thư giãn và dễ chịu hơn rất nhiều.",
    date: "28/04/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "guasha",
    userName: "Chị Ngọc",
    rating: 5,
    comment: "Mình thích nhất là cảm giác thư giãn sau khi guasha. Da mặt hồng hào hơn, tinh chất cũng thẩm thấu tốt hơn khi kết hợp cùng quy trình chăm sóc da.",
    date: "06/04/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "chai-kho-co-the",
    userName: "Chị Mai",
    rating: 5,
    comment: "Mình chải khô cơ thể trước khi tắm mỗi ngày, da mịn màng hơn hẳn và các vùng da sần ở tay chân cũng cải thiện rõ rệt. Ngoài ra giúp lưu thông hệ bạch huyết nên cơ thể năng lượng hơn rất nhiều.",
    date: "10/05/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "chai-kho-co-the",
    userName: "Chị Thảo",
    rating: 5,
    comment: "Ban đầu mình nghĩ chải khô sẽ khó chịu nhưng thực tế rất dễ chịu. Sau một thời gian da sáng khỏe hơn và cảm giác cơ thể nhẹ nhàng hơn.",
    date: "18/04/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "chai-kho-co-the",
    userName: "Chị Vy",
    rating: 5,
    comment: "Mình dùng chải khô kết hợp massage nhẹ trước khi tắm. Da mềm mượt hơn, các vùng da khô ráp ở khuỷu tay và đầu gối cũng giảm đáng kể.",
    date: "27/03/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "toner-hoa-hong",
    userName: "Chị Vân",
    rating: 5,
    comment: "Thơm mùi hoa hồng, dịu nhẹ cho da, mình để sẵn 1 chai ở công ty để xịt cấp ẩm khi làm việc phòng điều hòa. Thấy da cũng se lỗ chân lông lại",
    date: "21/05/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "toner-tia-to",
    userName: "Chị Châu",
    rating: 5,
    comment: "Xịt khoáng lành tính, xịt sau khi nặn mụn thấy dịu da hẳn, trời nắng xịt vài pump đã lắm",
    date: "21/05/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "toner-tia-to",
    userName: "Chị Tâm",
    rating: 5,
    comment: "Xịt khoáng thơm mùi tía tô, mình thích mấy sản phẩm lành tính, tự nhiên bản địa như thế này. Có 1 tip là để ở ngăn mát tủ lạnh xong lấy ra xịt thích lắm, giup giảm mụn và se lỗ chân lông nữa.",
    date: "29/04/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "toner-hoa-cuc",
    userName: "Chị Trà",
    rating: 5,
    comment: "Xịt khoáng mình thích nhất trong các loại xịt khoáng nước cất thảo mục. Nó thơm mùi hoa cúc lắm, trên thị trường cũng ít bên bán kiểu này. Mình mua cả 4 loại xịt khoáng dùng thử cho đã mà thsich nhất em này, giá cũng hạt dẻ nữa. Must try nha",
    date: "14/05/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "tinh-chat-hoa-buoi",
    userName: "Chị Khánh Huyền",
    rating: 5,
    comment: "Xịt khoáng này đa năng thật, mình mua để xịt tóc ai ngờ xịt được cả da mặt, thơm mùi hoa bưởi lắm nên có thể xịt lên body như body mist nhưng không lưu được hương lâu đâu. Đi đâu mình cũng mang theo 1 chai",
    date: "19/05/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "nuoc-tay-trang-tia-to-hoa-hong",
    userName: "Chị Lan Ngọc",
    rating: 5,
    comment: "Nước tẩy trang dịu nhẹ, phù hợp dùng khi không make up mà muốn làm sạch da mặt nhẹ nhàng còn nếu makeup thì nước không tẩy được nhé. Nhìn chung cũng giúp da cân bằng hơn, mình dùng hàng ngày vì mình cũng ko makeup.",
    date: "22/05/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "xa-bong-nghe-hoa-hong",
    userName: "Chị Minh Châu",
    rating: 5,
    comment: "Da mình khá nhạy cảm với sữa tắm công nghiệp nhưng dùng xà bông này lại thấy dễ chịu và không hề bị kích ứng. Da cũng mềm hơn sau khi tắm chứ không có cảm giác khô rít",
    date: "11/05/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "xa-bong-nghe-hoa-hong",
    userName: "Chị Hiền",
    rating: 5,
    comment: "Mình bị viêm nang lông nên hạn chế dùng sữa tắm công nghiệp, dùng xà bông này thấy khá ok, da mềm mịn hơn khá nhiều",
    date: "19/04/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "xa-bong-gung-tram-que",
    userName: "Chị Thanh",
    rating: 5,
    comment: "Mình bị mụn lưng lâu năm vậy mà dùng xà bông này lại hết mụn lưng, xà bông lành tính dịu nhẹ và hoàn toàn không có chất tẩy rửa mạnh hay hương liệu, an toàn để sử dụng",
    date: "14/05/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "xa-bong-gung-tram-que",
    userName: "Chị Vy",
    rating: 5,
    comment: "Mình mang bầu nên tìm đến các sản phẩm thiên nhiên, mình thay sữa tắm thành xà bông thiên nhiên ai dè mềm da quá trời, xà bông lành tính nên là mình dùng cho bé con nhà mình luôn",
    date: "22/04/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "mat-na-hoa-hong",
    userName: "Chị Lan",
    rating: 5,
    comment: "Mặt nạ hoa hồng dùng rất thích, da mình sau khi đắp cảm giác mềm mịn và đủ ẩm hơn hẳn. Sáng hôm sau da nhìn căng bóng tự nhiên.",
    date: "14/05/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "mat-na-hoa-hong",
    userName: "Chị Hương",
    rating: 5,
    comment: "Da mình khá nhạy cảm nhưng dùng mặt nạ này không bị châm chích hay kích ứng. Mỗi tuần đắp 2-3 lần thấy da tươi tắn và đều màu hơn.",
    date: "22/04/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "mat-na-hoa-hong",
    userName: "Chị Ngọc",
    rating: 5,
    comment: "Mùi hoa hồng dịu nhẹ rất thư giãn. Sau mỗi lần đắp da mềm, mịn , lỗ chân lông cũng được se khít. Mình bầu nên thích mấy đồ thiên nhiên kiểu này.",
    date: "31/03/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "mat-na-tia-to",
    userName: "Chị Mai",
    rating: 5,
    comment: "Da mình hay nổi mụn li ti và dễ xỉn màu. Sau một thời gian dùng mặt nạ tía tô thấy da sáng khỏe hơn, mụn cũng giảm đáng kể.",
    date: "14/05/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "mat-na-tia-to",
    userName: "Chị Thảo",
    rating: 5,
    comment: "Mình thích cảm giác sạch và thông thoáng sau khi đắp. Da bớt đổ dầu vùng chữ T và nhìn đều màu hơn.",
    date: "22/04/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "mat-na-tia-to",
    userName: "Chị Vy",
    rating: 5,
    comment: "Mặt nạ lành tính, không làm khô da. Dùng đều đặn thấy các vết thâm mụn mờ dần và da trông rạng rỡ hơn.",
    date: "31/03/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "mat-na-nghe-phuc-hoi",
    userName: "Chị Linh",
    rating: 5,
    comment: "Da mình sau mụn thường để lại thâm. Kiên trì sử dụng một thời gian thấy da sáng hơn và các vết thâm mờ dần.",
    date: "19/05/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "mat-na-nghe-phuc-hoi",
    userName: "Chị Kim",
    rating: 5,
    comment: "Mặt nạ giúp da mềm mại, không bị khô căng sau khi dùng. Mình rất thích vì cảm giác da được nuôi dưỡng và phục hồi tốt.",
    date: "27/04/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "dau-duong-hoa-hong",
    userName: "Chị Yến",
    rating: 5,
    comment: "Dầu massage thấm khá tốt, không quá nhờn rít. Sau khi massage da mềm và có cảm giác thư giãn dễ chịu. Mình mua kèm Guasha để dùng luôn",
    date: "18/05/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "dau-duong-hoa-hong",
    userName: "Chị Trang",
    rating: 5,
    comment: "Mùi hương hoa hồng nhẹ nhàng giúp mình thư giãn sau một ngày làm việc. Da cơ thể cũng mềm mượt hơn khi dùng thường xuyên.",
    date: "26/04/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "cao-goi-hoa-hong-2-in-1-goixa",
    userName: "Chị Nhung",
    rating: 5,
    comment: "Tóc mình dễ bết nhưng dùng cao gội này thấy da đầu sạch thoáng mà tóc vẫn mềm mượt. Rất tiện vì gội và xả trong một bước.",
    date: "12/05/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "cao-goi-hoa-hong-2-in-1-goixa",
    userName: "Chị Hạnh",
    rating: 5,
    comment: "Sau vài tuần sử dụng tóc giảm khô xơ, dễ chải hơn và không bị nặng tóc. Mùi hương tự nhiên rất dễ chịu, thành phần cũng rất tự nhiên không có hóa chất",
    date: "20/04/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "cao-goi-hoa-hong-2-in-1-goixa",
    userName: "Chị Quỳnh",
    rating: 5,
    comment: "Mình thích cảm giác tóc sạch nhưng không bị khô như nhiều loại dầu gội khác. Tóc mềm và có độ bóng khỏe tự nhiên.",
    date: "29/03/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "tra-hoa-hong",
    userName: "Chị Thanh",
    rating: 5,
    comment: "Mình uống trà hoa hồng mỗi tối thay cho trà sữa, hương thơm rất dễ chịu. Uống xong cảm giác thư thái hơn và ngủ ngon hơn trước.",
    date: "21/05/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "tra-hoa-hong",
    userName: "Chị Hương",
    rating: 5,
    comment: "Trà có vị thanh nhẹ, không gắt. Mình duy trì uống hằng ngày thấy cơ thể dễ chịu, da dẻ cũng tươi tắn hơn.",
    date: "29/04/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "tra-hoa-hong",
    userName: "Chị Mai",
    rating: 5,
    comment: "Mỗi khi căng thẳng công việc mình đều pha một tách trà hoa hồng. Vừa thơm vừa giúp mình thư giãn và có những phút nghỉ ngơi thật sự.",
    date: "07/04/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "tra-tia-to",
    userName: "Chị Lan",
    rating: 5,
    comment: "Mình thường uống trà tía tô sau bữa ăn, vị thảo mộc dễ uống và cảm giác cơ thể nhẹ nhàng, dễ chịu hơn.",
    date: "21/05/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "tra-tia-to",
    userName: "Chị Ngọc",
    rating: 5,
    comment: "Những ngày thời tiết thay đổi mình rất thích uống trà tía tô nóng. Hương thơm tự nhiên giúp cổ họng dễ chịu và tinh thần cũng thoải mái hơn. Khi thời tiết thay đổi dễ cảm sốt mình cũng dùng trà tía tô để giải cảm và giảm sốt nhanh chóng.",
    date: "29/04/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "tra-tia-to",
    userName: "Chị Thảo",
    rating: 5,
    comment: "Trà tía tô là loại trà mình luôn mang theo ở văn phòng. Vị thanh nhẹ, dễ uống và giúp mình bổ sung nước trong ngày một cách ngon miệng hơn. Uống đều thấy cơ thể nhẹ nhàng và da cũng sáng hơn.",
    date: "07/04/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "gac-len-men",
    userName: "Chị Hà Phương",
    rating: 5,
    comment: "Gấc tốt cho sức khỏe như thế nào thì ai cũng biết rồi, nhưng để ăn gấc hàng ngày thì hơi kho, biết đến món gấc mật ong lên men này thì đúng là chân ái, có thể ăn gấc mỗi ngày luôn. Mình thường pha nước uống hoặc ăn kèm như 1 lạo mứt với bánh mì vào buổi sáng, rất ngon",
    date: "15/05/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "gac-len-men",
    userName: "Chị Huyền Anh",
    rating: 5,
    comment: "Món gấc lên men này vừa giúp bổ sung lợi khuẩn đường ruột, vừa bổ sung omega 6 9 và beta caroten, bổ sung sắt cho người bị thiếu máu. Món gấc này được làm từ tất cả thịt gấc luôn nên đầy đủ dưỡng chất luôn, mình dùng đều đặn thấy nội tiết ổn hơn nhiều, da cũng đẹp hơn. Mà quan trọng là nó ngon",
    date: "23/04/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "mat-ong-gung-quat-muoi",
    userName: "Chị Mai",
    rating: 5,
    comment: "Những ngày thời tiết thay đổi mình thường pha một ly mật ong lên men gừng quất muối với nước ấm. Uống vào thấy cổ họng dễ chịu và ấm người hơn.",
    date: "09/05/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "mat-ong-gung-quat-muoi",
    userName: "Chị Thanh",
    rating: 5,
    comment: "Cả nhà mình đều thích sản phẩm này. Vị thơm tự nhiên, tiện sử dụng và đặc biệt phù hợp để dùng vào những ngày mưa lạnh. Mấy đứa bé nhà mình mỗi lần ho khò khè là mình lại pha cho tụi nhỏ 1 ly này với nước ấm là tụi nó đỡ hẵn, cũng có thể để ngậm ho hoặc chưng với lê ăn cũng giảm ho rất nhiều",
    date: "17/04/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "cot-nghe-mat-ong-len-men",
    userName: "Chị Linh Nguyễn",
    rating: 5,
    comment: "Mình dùng cốt nghệ mật ong lên men vào mỗi buổi sáng, vắt thêm ít chanh và thêm ít muối hạt. Ngày trước mình hay bị táo bón. uống đều thì cảm thấy ruột khỏe hơn nhiều, không bị táo bón, đi vệ sinh cũng đều đặn, cơ thể thấy nhẹ nhàng và ăn uống tốt hơn.",
    date: "19/05/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "cot-nghe-mat-ong-len-men",
    userName: "Chị Hạnh Tâm",
    rating: 5,
    comment: "Sau một thời gian sử dụng đều đặn, mình cảm thấy cơ thể nhẹ nhàng hơn, chắc do ruột khỏe và sạch hơn nên da cũng sáng hơn. Mình cũng cho chồng uống vào buổi sáng cũng mình luôn, chồng mình từ người bị men gan cao thì giờ gan đã trở về mức bình thường sau 2 tháng sử dụng.",
    date: "27/04/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "cot-nghe-mat-ong-len-men",
    userName: "Chị Phương",
    rating: 5,
    comment: "Rất nên có 1 chai này trong gia đình, chỉ cần uống vào buổi sáng khi bụng rỗng liên tục trong 2-3 tháng là thấy sự cải thiện rất nhiều. Mình bị đau dạ dày sau khi kiền trì uống đã cải thiện rất nhiều",
    date: "05/04/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "cot-nghe-mat-ong-len-men",
    userName: "Chị Liên",
    rating: 5,
    comment: "Mình bị trào ngược dạ dày lâu năm, sau khi dùng món cốt nghệ mật ong kên men này thì không còn bị trào ngược nữa. Uống vào buổi sáng như được rửa sạch dạ dày và ruột. Mà uống khá ngon chứ không bị mùi nghệ nồng.",
    date: "14/03/2026",
    isVerifiedPurchase: true
  },
  {
    productId: "cot-nghe-mat-ong-len-men",
    userName: "Chị Diễm",
    rating: 5,
    comment: "Món nghệ này phụ nữ rất nên dùng nhé, vừa khỏe bên trong mà đẹp bên ngoài. Mình uống đều đặn 1 năm khoảng 3-4 đợt, mỗi đợt 2 tháng, việc tiêu hóa và thải độc chất cặn trong ruột rất tốt, da hồng hào sáng khỏe, hết cả mụn lưng. Kinh nguyệt cũng đều hơn nữa.",
    date: "20/02/2026",
    isVerifiedPurchase: true
  },
];
